version: "3.4"
services:
  juiceman.dnp.dappnode.eth:
    image: "juiceman.dnp.dappnode.eth:0.1.0"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.10.13-mev0.4.1
    volumes:
      - "geth:/root/.ethereum"
    environment:
      - "EXTRA_OPTIONS=--http.api eth,net,web3,txpool --ws.api eth,net,web3,txpool"
      - SYNCMODE=light
    ports:
      - "30303"
      - 30303/udp
      - 30304/udp
    restart: unless-stopped
volumes:
  geth: {}
